Repository devin-efendy/fujiji, pull requests merged in 2022-04, with the labels that each got.

#118 feat/#107: Create Comment component
  fujiji-client/src/components/Comment/Comment.jsx
  fujiji-client/src/components/Comment/Comment.spec.jsx
  fujiji-client/src/components/Comment/Comment.stories.jsx
  fujiji-client/src/components/index.js
  fujiji-client/src/server/api/index.js
  fujiji-client/src/server/api/updateComment.js
  fujiji-server/src/controllers/comment.js
Labels: task, front-end

#122 feat/#108: Create comment form component
  fujiji-client/src/components/CommentForm/CommentForm.jsx
  fujiji-client/src/components/CommentForm/CommentForm.spec.jsx
  fujiji-client/src/components/CommentForm/CommentForm.stories.jsx
  fujiji-client/src/server/api/postComment.js
Labels: task, front-end

#121 chore/dockerized Fujiji client
  fujiji-client/.dockerignore
  fujiji-client/Dockerfile
  fujiji-client/docker-compose.yaml
Labels: task, front-end

#124 feat/#109: add comment section to individual listing page
  fujiji-client/src/components/Comment/Comment.jsx
  fujiji-client/src/components/Comment/Comment.spec.jsx
  fujiji-client/src/components/Comment/Comment.stories.jsx
  fujiji-client/src/components/CommentForm/CommentForm.jsx
  fujiji-client/src/components/index.js
  fujiji-client/src/pages/listing/[id].jsx
  fujiji-client/src/server/api/getCommentsByListingId.js
  fujiji-client/src/server/api/index.js
Labels: front-end

#125 Fix/#94: Validate matching city and province
  fujiji-client/src/components/ListingForm/ListingForm.jsx
  fujiji-client/src/components/ListingForm/ListingForm.spec.jsx
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/errors/listing/index.js
  fujiji-server/src/errors/listing/listingInvalidCityProvince.js
Labels: bug, back-end

#129 Feat/#128: My Listings shows a selected listing with Edit button first
  fujiji-client/src/pages/user/[userId]/listings.jsx
Labels: bug, front-end

#132 Chore/Added create fujiji_comments to migration script
  fujiji-server/migration-scripts/down.sql
  fujiji-server/migration-scripts/up.sql
Labels: task, back-end

#133 chore: setup local DB
  fujiji-server/Dockerfile.dev
  fujiji-server/docker-compose.yaml
  fujiji-server/migration-scripts/up.sql
Labels: database

#134 Implemented DEL comment endpoint
  fujiji-server/__test__/controllers/comment.test.js
  fujiji-server/package-lock.json
  fujiji-server/src/controllers/comment.js
  fujiji-server/src/repositories/comment.js
  fujiji-server/src/routes/comment.js
  package-lock.json
Labels: task, back-end

#135 Upload our own image to the listings
  fujiji-client/package-lock.json
  fujiji-client/package.json
  fujiji-client/src/components/ListingForm/ListingForm.jsx
  fujiji-client/src/components/ListingForm/ListingForm.spec.jsx
  fujiji-client/src/pages/listing/create.jsx
  fujiji-client/src/pages/listing/edit/[id].jsx
  fujiji-client/src/server/api/index.js
  fujiji-client/src/server/api/uploadImage.js
Labels: bug, front-end

#138 feat/#137: Implement delete comment button
  fujiji-client/src/components/Comment/Comment.jsx
  fujiji-client/src/components/Comment/Comment.spec.jsx
  fujiji-client/src/server/api/deleteCommentById.js
  fujiji-client/src/server/api/index.js
Labels: front-end

#144 Feat/#142 Create boost & boost_package tables
  fujiji-server/migration-scripts/down.sql
  fujiji-server/migration-scripts/example.sql
  fujiji-server/migration-scripts/up.sql
Labels: task, database

#147 feat/#145: implement boost indicator
  fujiji-client/src/components/AdListingCard/AdListingCard.jsx
  fujiji-client/src/components/AdListingCard/AdListingCard.spec.jsx
  fujiji-client/src/components/AdListingCard/AdListingCard.stories.jsx
  fujiji-client/src/components/Listing/Listing.jsx
  fujiji-client/src/components/Listing/Listing.spec.jsx
  fujiji-client/src/components/Listing/Listing.stories.jsx
  fujiji-client/src/pages/search/index.jsx
Labels: front-end

#151 feat/#150: Create boost package selection component
  fujiji-client/src/components/BoostPackageSelection/BoostPackageSelection.jsx
  fujiji-client/src/components/BoostPackageSelection/BoostPackageSelection.spec.jsx
  fujiji-client/src/components/BoostPackageSelection/BoostPackageSelection.stories.jsx
  fujiji-client/src/components/Listing/Listing.jsx
  fujiji-client/src/components/index.js
Labels: front-end

#152 Implemented POST boost endpoint
  fujiji-server/__test__/controllers/boost.test.js
  fujiji-server/migration-scripts/example.sql
  fujiji-server/package-lock.json
  fujiji-server/src/controllers/boost.js
  fujiji-server/src/errors/boost/index.js
  fujiji-server/src/errors/boost/packageNotFound.js
  fujiji-server/src/errors/index.js
  fujiji-server/src/repositories/boost.js
  fujiji-server/src/repositories/boost_package.js
  fujiji-server/src/routes/boost.js
  fujiji-server/src/routes/index.js
Labels: task, back-end

#159 Chore/server load test
  fujiji-server/.eslintrc.json
  fujiji-server/__test__/load-test/load-test.yaml
  fujiji-server/__test__/load-test/processor.js
  fujiji-server/__test__/load-test/report.html
  fujiji-server/package-lock.json
  fujiji-server/package.json
Labels: task, back-end

#157 Fixed CodeQL Azure Pipeline to run correctly
  .github/codeql/codeql-config.yml
  codeql-azure-pipeline.yml
  fujiji-server/src/controllers/listing.js
Labels: task

#162 Feat/#160 Implemented comment's reply endpoint
  fujiji-server/__test__/controllers/comment.test.js
  fujiji-server/__test__/dbSetup.js
  fujiji-server/migration-scripts/add_comment_reply.sql
  fujiji-server/migration-scripts/example.sql
  fujiji-server/migration-scripts/up.sql
  fujiji-server/src/controllers/comment.js
  fujiji-server/src/repositories/comment.js
  fujiji-server/src/routes/comment.js
Labels: task, back-end

#163 feat/#161: create single nested comment reply
  fujiji-client/src/components/Comment/Comment.jsx
  fujiji-client/src/components/Comment/Comment.spec.jsx
  fujiji-client/src/components/Comment/Comment.stories.jsx
  fujiji-client/src/components/CommentForm/CommentForm.jsx
  fujiji-client/src/components/CommentForm/CommentForm.spec.jsx
  fujiji-client/src/components/CommentForm/CommentForm.stories.jsx
  fujiji-client/src/pages/listing/[id].jsx
  fujiji-client/src/server/api/deleteCommentReplyById.js
  fujiji-client/src/server/api/getCommentsByListingId.js
  fujiji-client/src/server/api/getListingById.js
  fujiji-client/src/server/api/index.js
  fujiji-client/src/server/api/replyComment.js
Labels: front-end

#166 Update GET listing endpoints to include boost score
  fujiji-server/__test__/controllers/boost.test.js
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/package-lock.json
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/repositories/boost.js
Labels: task, back-end

#165 Create a boost for ad listing by making a payment
  azure-pipelines-ui.yml
  fujiji-client/.env.production
  fujiji-client/.env.sample
  fujiji-client/next.config.js
  fujiji-client/package-lock.json
  fujiji-client/package.json
  fujiji-client/src/components/BoostPackageSelection/BoostPackageSelection.jsx
  fujiji-client/src/components/BoostPackageSelection/BoostPackageSelection.spec.jsx
  fujiji-client/src/components/Listing/Listing.jsx
  fujiji-client/src/components/Listing/Listing.spec.jsx
  fujiji-client/src/components/Stripe/Stripe.jsx
  fujiji-client/src/pages/api/checkout_sessions.js
  fujiji-client/src/server/api/index.js
  fujiji-client/src/server/api/postBoost.js
  fujiji-server/__test__/controllers/boost.test.js
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/src/controllers/boost.js
  fujiji-server/src/errors/boost/boostAlreadyExists.js
  fujiji-server/src/errors/boost/index.js
  fujiji-server/src/repositories/boost.js
Labels: front-end

#168 feat/#167: show boost indicator on pages
  fujiji-client/src/pages/listing/[id].jsx
  fujiji-client/src/pages/user/[userId]/listings.jsx
  fujiji-client/src/server/api/getListingById.js
  fujiji-client/src/server/api/getListingByUserId.js
  fujiji-server/package.json
  fujiji-server/src/controllers/user.js
Labels: task, front-end

#170 Sort listings based on score and creation date
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/repositories/listing.js
Labels: task, back-end

#171 chore/update-docs-with-chat-feature
  README.md
  docs/block-diagram.png
  docs/class-diagram.png
Labels: documentation

#172 fix/storybook is broken because useRouter
  fujiji-client/src/components/Listing/Listing.jsx
Labels: bug

#183 fix: go to chat button on listing
  fujiji-client/src/components/Listing/Listing.jsx
Labels: front-end
