Repository devin-efendy/fujiji, pull requests merged in 2022-03, with the labels that each got.

#61 Feat/13 create get listings endpoint
  fujiji-server/.eslintrc.json
  fujiji-server/README.md
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/package.json
  fujiji-server/src/app.js
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/errors/api.js
  fujiji-server/src/errors/listing/listingLocationUndefined.js
  fujiji-server/src/errors/listing/listingNotFound.js
  fujiji-server/src/repositories/listing.js
  fujiji-server/src/routes/index.js
  fujiji-server/src/routes/listing.js
Labels: back-end

#66 feat/#63: implement auth endpoints
  fujiji-server/.env.test
  fujiji-server/__test__/controllers/auth.test.js
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/__test__/dbSetup.js
  fujiji-server/migration-scripts/up.sql
  fujiji-server/package.json
  fujiji-server/src/app.js
  fujiji-server/src/config/config.js
  fujiji-server/src/controllers/auth.js
  fujiji-server/src/errors/auth/EmailAlreadyRegistredError.js
  fujiji-server/src/errors/auth/InvalidPasswordError.js
  fujiji-server/src/errors/auth/InvalidTokenError.js
  fujiji-server/src/errors/auth/UserNotFoundError.js
  fujiji-server/src/errors/auth/index.js
  fujiji-server/src/errors/index.js
  fujiji-server/src/middleware/apiError.js
  fujiji-server/src/middleware/authentication.js
  fujiji-server/src/models/index.js
  fujiji-server/src/models/user.js
  fujiji-server/src/repositories/auth.js
  fujiji-server/src/repositories/db.js
  fujiji-server/src/repositories/listing.js
  fujiji-server/src/repositories/user.js
  fujiji-server/src/routes/auth.js
  fujiji-server/src/routes/index.js
Labels: task, back-end

#68 Navigation bar to use chakra and new design
  fujiji-client/package-lock.json
  fujiji-client/src/components/NavBar/NavBar.jsx
  fujiji-client/src/components/NavBar/NavBar.module.css
  fujiji-client/src/pages/_app.jsx
  fujiji-client/src/pages/index.jsx
  fujiji-client/src/pages/search.jsx
  fujiji-client/src/utils/theme.js
Labels: front-end

#72 Feat/#12 create endpoint for posting listings
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/repositories/listing.js
  fujiji-server/src/routes/listing.js
Labels: back-end

#73 feat/#7-create-sign-in-page
  fujiji-client/.env.test
  fujiji-client/config/index.js
  fujiji-client/next.config.js
  fujiji-client/package.json
  fujiji-client/src/components/NavBar/NavBar.jsx
  fujiji-client/src/components/NavBar/NavBar.stories.jsx
  fujiji-client/src/components/PageLayout/PageLayout.jsx
  fujiji-client/src/components/SignIn/SignIn.jsx
  fujiji-client/src/components/SignIn/SignIn.spec.jsx
  fujiji-client/src/context/session.js
  fujiji-client/src/hooks/useSessionHook.js
  fujiji-client/src/pages/_app.jsx
  fujiji-client/src/pages/index.jsx
  fujiji-client/src/pages/signin/index.jsx
  fujiji-client/src/pages/signup/index.jsx
  fujiji-client/src/server/api/index.js
  fujiji-client/src/server/api/signIn.js
  fujiji-client/src/server/api/signUp.js
  fujiji-client/src/utils/getQueryString.js
  fujiji-client/src/utils/validate.js
  fujiji-server/__test__/controllers/auth.test.js
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/package.json
  fujiji-server/src/app.js
  fujiji-server/src/controllers/auth.js
  fujiji-server/src/errors/auth/InvalidPasswordError.js
  fujiji-server/src/routes/auth.js
  fujiji-server/src/utils/logging.js
Labels: front-end

#74 Landing page
  fujiji-client/.env.test
  fujiji-client/package-lock.json
  fujiji-client/src/components/NavBar/NavBar.jsx
  fujiji-client/src/pages/index.jsx
  fujiji-client/src/utils/theme.js
Labels: front-end

#76 fix/cors-issue-on-client
  fujiji-client/.env.sample
  fujiji-client/.env.test
  fujiji-client/README.md
  fujiji-client/src/components/SignIn/SignIn.jsx
  fujiji-client/src/server/api/signIn.js
  fujiji-client/src/server/api/signUp.js
  fujiji-server/.env.sample
  fujiji-server/README.md
Labels: bug

#78 update-diagrams-for-ms2
  docs/block-diagram.png
  docs/class-diagram.png
  docs/drawio/block-diagram.drawio
  docs/drawio/class-diagram.drawio
  docs/workflow-diagram.png
Labels: documentation

#80 Added Fujiji Test Plan
  docs/FujijiTestPlan.pdf
Labels: documentation

#81 Feat/#17 create endpoint for editing a list
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/package-lock.json
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/repositories/listing.js
  fujiji-server/src/routes/listing.js
Labels: back-end

#82 feat/#15-create-post-and-edit-listing-page
  fujiji-client/.env.sample
  fujiji-client/config/index.js
  fujiji-client/package-lock.json
  fujiji-client/package.json
  fujiji-client/src/components/ListingForm/ListingForm.jsx
  fujiji-client/src/components/ListingForm/ListingForm.spec.jsx
  fujiji-client/src/components/NavBar/NavBar.jsx
  fujiji-client/src/components/NavBar/NavBar.stories.jsx
  fujiji-client/src/components/PageLayout/PageLayout.jsx
  fujiji-client/src/components/RequireAuthDialog/RequireAuthDialog.jsx
  fujiji-client/src/components/RequireAuthDialog/RequireAuthDialog.stories.jsx
  fujiji-client/src/components/SignIn/SignIn.jsx
  fujiji-client/src/components/index.js
  fujiji-client/src/components/withSession/withSession.jsx
  fujiji-client/src/context/session.js
  fujiji-client/src/pages/_app.jsx
  fujiji-client/src/pages/listing/[id].jsx
  fujiji-client/src/pages/listing/create.jsx
  fujiji-client/src/server/api/deleteListingById.js
  fujiji-client/src/server/api/getListingById.js
  fujiji-client/src/server/api/index.js
  fujiji-client/src/server/api/postListing.js
  fujiji-client/src/server/api/updateListing.js
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/repositories/listing.js
  fujiji-server/src/routes/listing.js
Labels: task, front-end, back-end

#84 Feat/55 implement GET /user/[id] and /user/[id]/listings
  fujiji-server/__test__/controllers/listing.test.js
  fujiji-server/__test__/controllers/user.test.js
  fujiji-server/src/controllers/listing.js
  fujiji-server/src/controllers/user.js
  fujiji-server/src/errors/listing/listingLocationUndefined.js
  fujiji-server/src/errors/user/invalidUserID.js
  fujiji-server/src/errors/user/userListingsNotFound.js
  fujiji-server/src/errors/user/userNotFound.js
  fujiji-server/src/repositories/user.js
  fujiji-server/src/routes/user.js
Labels: task, back-end

#86 feat/#83: Build My Listings page for sellers
  fujiji-client/src/components/ListingForm/ListingForm.jsx
  fujiji-client/src/components/NavBar/NavBar.jsx
  fujiji-client/src/pages/listing/create.jsx
  fujiji-client/src/pages/listing/edit/[id].jsx
  fujiji-client/src/pages/user/[userId]/listings.jsx
  fujiji-client/src/server/api/getListingByUserId.js
  fujiji-client/src/server/api/index.js
  fujiji-server/__test__/controllers/user.test.js
  fujiji-server/src/repositories/user.js
Labels: task, front-end, back-end

#88 Feat/#85 Created edit user profile endpoint
  fujiji-server/__test__/controllers/user.test.js
  fujiji-server/src/controllers/user.js
  fujiji-server/src/repositories/user.js
  fujiji-server/src/routes/user.js
Labels: task, back-end

#89 feat/#87: Page for showcase individual listing
  fujiji-client/src/__mocks__/mockAdListing.js
  fujiji-client/src/components/AdListingCard/AdListingCard.jsx
  fujiji-client/src/components/Listing/Listing.jsx
  fujiji-client/src/pages/listing/[id].jsx
  fujiji-client/src/server/api/getListingById.js
  fujiji-client/src/server/api/getListingByUserId.js
  fujiji-server/src/controllers/listing.js
Labels: task, front-end, back-end

#90 Create Edit Profile Page and fix the edit user endpoint to be consistent with other endpoints
  fujiji-client/src/components/EditProfile/EditProfile.jsx
  fujiji-client/src/components/EditProfile/EditProfile.stories.jsx
  fujiji-client/src/pages/profile/index.jsx
  fujiji-client/src/server/api/editProfile.js
  fujiji-client/src/server/api/index.js
  fujiji-server/__test__/controllers/user.test.js
  fujiji-server/src/controllers/user.js
Labels: front-end

#97 fix/#96: ConditionBadge crashing because unrecognized switch condition
  fujiji-client/src/components/ListingForm/ListingForm.jsx
  fujiji-client/src/components/ListingForm/ListingForm.spec.jsx
Labels: bug, front-end

#98 Search page that shows all listings
  fujiji-client/package-lock.json
  fujiji-client/src/pages/search.jsx
  fujiji-client/src/pages/search/index.jsx
  fujiji-client/src/server/api/getAllListings.js
  fujiji-client/src/server/api/index.js
Labels: front-end

#110 chore/storybook-showcase
  fujiji-client/package-lock.json
  fujiji-client/package.json
Labels: task, front-end

#112 chore: clean-up Storybook
  azure-pipelines-storybook.yml
  fujiji-client/src/__mocks__/mockAdListing.js
  fujiji-client/src/components/AdListingCard/AdListingCard.jsx
  fujiji-client/src/components/AdListingCard/AdListingCard.stories.jsx
  fujiji-client/src/components/EditProfile/EditProfile.jsx
  fujiji-client/src/components/EditProfile/EditProfile.stories.jsx
  fujiji-client/src/components/NavBar/NavBar.stories.jsx
  fujiji-client/src/components/SignIn/SignIn.stories.jsx
  fujiji-client/src/components/index.js
  fujiji-client/src/pages/profile/index.jsx
Labels: front-end

#116 feat/#104: implement POST comment endpoint
  fujiji-server/__test__/controllers/comment.test.js
  fujiji-server/migration-scripts/fix_isAuthor_typo.sql
  fujiji-server/src/app.js
  fujiji-server/src/config/config.js
  fujiji-server/src/controllers/comment.js
  fujiji-server/src/errors/index.js
  fujiji-server/src/errors/listing/index.js
  fujiji-server/src/errors/user/userNotFound.js
  fujiji-server/src/repositories/comment.js
  fujiji-server/src/routes/comment.js
  fujiji-server/src/routes/index.js
  fujiji-server/src/utils/logging.js
Labels: task, back-end

#115 fix/#92: Show edit button for seller in the individual listing page
  fujiji-client/.eslintrc
  fujiji-client/src/components/Listing/Listing.jsx
  fujiji-client/src/components/Listing/Listing.spec.jsx
  fujiji-client/src/components/Listing/Listing.stories.jsx
  fujiji-client/src/pages/listing/[id].jsx
  fujiji-client/src/pages/search/index.jsx
Labels: bug, front-end

#117 Feat/#103 implement GET comment endpoint
  fujiji-server/__test__/controllers/comment.test.js
  fujiji-server/migration-scripts/add_comment_modified_date.sql
  fujiji-server/src/controllers/comment.js
  fujiji-server/src/repositories/comment.js
  fujiji-server/src/routes/comment.js
Labels: task, back-end
